# Numpy Library function

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## ARange 

### Return evenly spaced values within a given interval

In [7]:
# Creates array from range 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Creates array from range 0 to 10 and increase at interval
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# The method zeros createsan array of specified
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# The method ones creates an array at specified length
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Eye

### Creates an identity matrix

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

In [15]:
np.random.rand(2)

array([0.75172553, 0.74223531])

In [17]:
np.random.rand(5,5)

array([[0.01890981, 0.56950012, 0.56249152, 0.92993469, 0.31115716],
       [0.14150813, 0.45044941, 0.27721658, 0.31163153, 0.97591108],
       [0.50402216, 0.81747151, 0.92752377, 0.80066322, 0.40079409],
       [0.01923903, 0.23883849, 0.94686762, 0.44770307, 0.76625901],
       [0.48204852, 0.457274  , 0.51812334, 0.4249654 , 0.75829672]])

### Array Attributes and methods

In [43]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr

array([ 7, 18, 14, 17, 14, 48, 10, 34, 45, 35])

In [22]:
ranarr.max()

45

In [23]:
ranarr.argmax()

7

In [24]:
ranarr.min()

0

In [25]:
ranarr.argmin()

9

## Excersice

In [26]:
import numpy as np

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
my_matrix = [5,5,5,5,5,5,5,5,5,5]

In [38]:
np.array(my_matrix)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [45]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [46]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])